package third.year.project;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.IIOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author charlierushton
 */
public class PrototypeGUI extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationGUI
     */
    public PrototypeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        buttonCopy = new javax.swing.JButton();
        textPassOutput = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        programHeader = new javax.swing.JLabel();
        buttonSelectImage = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textImagePath = new javax.swing.JTextArea();
        labelPin = new javax.swing.JLabel();
        labelPassLength = new javax.swing.JLabel();
        spinnerPassLength = new javax.swing.JSpinner();
        buttonGenerate = new javax.swing.JButton();
        textPin = new javax.swing.JTextField();

        jFileChooser1.setDialogTitle("Choose an image...");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image-Based Password Generator");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(116, 185, 255));
        jPanel4.setAutoscrolls(true);

        buttonCopy.setFont(new java.awt.Font("Lao Sangam MN", 0, 13)); // NOI18N
        buttonCopy.setLabel("Copy to Clipboard");
        buttonCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCopyActionPerformed(evt);
            }
        });

        textPassOutput.setFont(new java.awt.Font("Lao Sangam MN", 0, 13)); // NOI18N
        textPassOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPassOutputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(textPassOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonCopy)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCopy)
                    .addComponent(textPassOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(178, 190, 195));

        programHeader.setFont(new java.awt.Font("Lao Sangam MN", 0, 24)); // NOI18N
        programHeader.setText("Image-Based Password Generator");

        buttonSelectImage.setBackground(new java.awt.Color(178, 190, 195));
        buttonSelectImage.setFont(new java.awt.Font("Lao Sangam MN", 0, 13)); // NOI18N
        buttonSelectImage.setText("Select Image...");
        buttonSelectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectImageActionPerformed(evt);
            }
        });

        textImagePath.setColumns(20);
        textImagePath.setFont(new java.awt.Font("Lao Sangam MN", 0, 13)); // NOI18N
        textImagePath.setRows(5);
        jScrollPane2.setViewportView(textImagePath);

        labelPin.setFont(new java.awt.Font("Lao Sangam MN", 0, 13)); // NOI18N
        labelPin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPin.setText("Enter Pin");

        labelPassLength.setFont(new java.awt.Font("Lao Sangam MN", 0, 13)); // NOI18N
        labelPassLength.setText("Password Length");

        spinnerPassLength.setFont(new java.awt.Font("Lao Sangam MN", 0, 13)); // NOI18N
        spinnerPassLength.setModel(new javax.swing.SpinnerNumberModel(8, 8, 64, 1));
        spinnerPassLength.setValue(8);

        buttonGenerate.setFont(new java.awt.Font("Lao Sangam MN", 0, 13)); // NOI18N
        buttonGenerate.setLabel("Generate!");
        buttonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSelectImage)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textPin)
                        .addComponent(programHeader)
                        .addComponent(buttonGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spinnerPassLength, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelPassLength)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                        .addComponent(labelPin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(programHeader)
                .addGap(18, 18, 18)
                .addComponent(buttonSelectImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPassLength)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerPassLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonGenerate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCopyActionPerformed
        StringSelection selection = new StringSelection(textPassOutput.getText());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);

        JOptionPane.showMessageDialog(null, "Password copied to clipboard!");
    }//GEN-LAST:event_buttonCopyActionPerformed

    private void buttonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerateActionPerformed
        try {
            int passwordLength = (Integer) spinnerPassLength.getValue();
            int lengthOfPin = textPin.getText().length();
            if (lengthOfPin < 6) {
                throw new PinException("Pin too short");
            }
            if (lengthOfPin > 10) {
                throw new PinException("Pin too long");
            }

            String password = ImagePinCombo.ImagePinCombo(
                    Integer.parseInt(textPin.getText()),
                    textImagePath.getText());
            String newPassword = password.substring(0, passwordLength);
            
            // Create new char array and insert password
            char[] changeCase = new char[]{};
            changeCase = newPassword.toCharArray();
            
            // Iterate through char array
            for (int i = 0; i < changeCase.length - 1; i++) {
                // If position in char array contains number 0 - 9
                if ((int) changeCase[i] >= 48 && (int) changeCase[i] <= 57) {
                    // If number is odd
                    if ((int) changeCase[i] % 2 != 0
                            // If pos+1 is lowercase letter
                            && (int) changeCase[i + 1] >= 97
                            && (int) changeCase[i + 1] <= 122) {
                        // Capitalise pos+1
                        changeCase[i + 1] -= 32;
                    }
                }

                newPassword = new String(changeCase);
                textPassOutput.setText(newPassword);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Pin number must be included and must be numbers (0-9) only!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Unsupported file type!");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Unsupported file type!");
        } catch (PinException e) {
            JOptionPane.showMessageDialog(null, "Your pin number must be longer than 6 digits and be no more than 10 digits!");
        } catch (Exception ex) {
            Logger.getLogger(PrototypeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buttonGenerateActionPerformed

    private void textPassOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPassOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPassOutputActionPerformed

    private void buttonSelectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectImageActionPerformed

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif", "bmp", "wbmp");
        jFileChooser1.setFileFilter(filter);
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            textImagePath.setText(jFileChooser1.getSelectedFile()
                    .getAbsolutePath());
        }
    }//GEN-LAST:event_buttonSelectImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrototypeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrototypeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrototypeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrototypeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrototypeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCopy;
    private javax.swing.JButton buttonGenerate;
    private javax.swing.JButton buttonSelectImage;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelPassLength;
    private javax.swing.JLabel labelPin;
    private javax.swing.JLabel programHeader;
    private javax.swing.JSpinner spinnerPassLength;
    private javax.swing.JTextArea textImagePath;
    private javax.swing.JTextField textPassOutput;
    private javax.swing.JTextField textPin;
    // End of variables declaration//GEN-END:variables
}
